version: '3.4'

services:
  app:
    build: .
    ports:
      - 3000:3000
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      # - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      # - POSTGRES_DB: postgres
